### ISSUE TITLE
关于JWT_BLACKLIST_GRACE_PERIOD和JWT_REFRESH_TTL配置项的问题

### ISSUE THREAD

**Issue by PanNinan** [hyperf-ext/jwt#16]
当JWT_BLACKLIST_GRACE_PERIOD和JWT_REFRESH_TTL配置项在env文件中配置时报错

/hyperf-ext/jwt/src/ManagerFactory.php文件62,63行,从config中取出的值类型为string,Blacklist类期望的值类型为int

建议获取配置项的时候可以(int)强制转换

![微信截图_20210617145628](https://user-images.githubusercontent.com/25807498/122347252-6d34c000-cf7c-11eb-8368-136e48447370.png)
![微信截图_20210617145729](https://user-images.githubusercontent.com/25807498/122347264-6f971a00-cf7c-11eb-8e44-9744bf41ca2e.png)

**Comment by EricYChu** [comment]
fixed @ https://github.com/hyperf-ext/jwt/commit/a4ecda6ee0bdaf1ffceabe2c4586d4a35d6ed824

**Comment by PanNinan** [comment]
@EricYChu 3Q~
