### ISSUE TITLE
疑似内存泄漏问题

### ISSUE THREAD

**Issue by canren** [hyperf-ext/jwt#18]
使用版本 hyperf-ext/jwt 版本v2.1.*

每次请求接口,经过 `jwt组件` 的  `HyperfExt\Jwt\Jwt::getParser(): Parser` 方法时, 下面代码

```php
    /**
     * Get the parser instance.
     */
    protected function getParser(): Parser
    {
        return new Parser();
    }
```

内存就会泄漏

包 `lcobucci/jwt` 的 `Lcobucci\JWT\Claim\Factory::__construct(array $callbacks = [])` 存在循环引用问题,内存不会被释放

**Comment by canren** [comment]
我修改了一下 `Lcobucci`, 提交了 `pr`, 不知道是否会给修复

**Comment by canren** [comment]
V4版本解决了这个问题,作者建议升级 `V4` 版本,[https://github.com/lcobucci/jwt/pull/771](url)

**Comment by EricYChu** [comment]
更新了。
