### ISSUE TITLE
其实你升级后的hyperf都改为2.2了是没必要的

### ISSUE THREAD

**Issue by ljyljy0211** [hyperf-ext/jwt#20]
其实你升级后的hyperf都改为2.2了是没必要的，应该依赖是大于等于Hyper的2.1版本就行了，因为jwt部分依赖的lcobucci/jwt，主要影响的是jwt的内存溢出，其他并没有差别，毕竟hyperf2.2现在还不稳定

**Comment by ericyzhu** [comment]
https://github.com/hyperf-ext/jwt/pull/21
