### ISSUE TITLE
文档错误,依赖的jwt库和composer中不一致

### ISSUE THREAD

**Issue by leihenshang** [hyperf-ext/jwt#5]
文档写到：
该组件基于 tymon/jwt-auth，实现了完整用于 JWT 认证的能力

实际在composer.json中:

   "require": {
        **"lcobucci/jwt": "~3.3.0",**
    },

而且最底部说到的两个类是什么，没看懂？

**Comment by EricYChu** [comment]
这个组件是基于 `tymon/jwt-auth` 这个 Laravel 组件的原始代码开发的，`lcobucci/jwt` 是实现 JWT 编解码的包。
示例中的两个类的作用已经在注释中写明了。

**Comment by leihenshang** [comment]
好的。不过下面说的两个类还是不是很清楚。
